backend:
  name: git-gateway
  branch: main

media_folder: 'assets/uploads'
public_folder: '/assets/uploads'

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'content/home.md'
        label: 'Home Page'
        name: 'home'
        fields:
          - { label: 'Hero Title', name: 'hero_title', widget: 'string' }
          - { label: 'Hero Text', name: 'hero_text', widget: 'text' }

      - file: 'content/about.md'
        label: 'About'
        name: 'about'
        fields:
          - { label: 'Content', name: 'body', widget: 'markdown' }
